const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const labelCartItems = () => { const counts = {}; Cart.detailed().forEach((box, i) => { counts[box.name] = (counts[box.name] || 0) + 1; const title = document.querySelectorAll(".cart-item h3")[i]; if (title) title.textContent = box.name + " " + counts[box.name]; }); };
const money = amount => `${amount.toLocaleString("en-US")} ${BUSINESS_CONFIG.currency}`;
const product = PRODUCTS[0];
const maxSentence = value => { let count = 0; return [...value].filter(char => /\s/.test(char) || ++count <= 30).join(""); };
function productCard() {
  const grid = $("[data-products]");
  if (!grid) return;
  grid.innerHTML = `<article class="product-card"><div class="product-view" data-view="${product.id}"><div class="product-image home-gallery"><img src="${product.gallery[0]}" alt="${product.name}" loading="eager" fetchpriority="high" decoding="async"><button class="gallery-arrow gallery-prev" type="button" data-home-prev aria-label="Previous image">‹</button><button class="gallery-arrow gallery-next" type="button" data-home-next aria-label="Next image">›</button><div class="gallery-dots" data-home-dots></div></div><div class="product-meta"><span class="product-pieces">${product.pieces} PIECES</span><h3>${product.name}</h3><p>${product.description}</p><strong>${money(product.price)} <small>/ box</small></strong></div></div><button class="add-button" data-view="${product.id}">Choose boxes</button></article>`;
  const image = grid.querySelector(".home-gallery img"), dots = grid.querySelector("[data-home-dots]"), images = product.gallery; let index = 0, timer;
  dots.innerHTML = images.map((_, i) => `<button type="button" data-home-dot aria-label="Show image ${i + 1}"></button>`).join("");
  const show = next => { index = (next + images.length) % images.length; image.src = images[index]; dots.querySelectorAll("button").forEach((dot, i) => dot.classList.toggle("is-active", i === index)); };
  const restart = () => { clearInterval(timer); timer = setInterval(() => show(index + 1), index === 0 ? 5500 : 4500); };
  const second = PRODUCTS[1];
  if (second) grid.insertAdjacentHTML("beforeend", `<article class="product-card"><div class="product-view" data-view="${second.id}"><div class="product-image"><img src="${second.image}" alt="${second.name}" loading="lazy" decoding="async"></div><div class="product-meta"><span class="product-pieces">${second.pieces} PIECES</span><h3>${second.name}</h3><p>${second.description}</p><strong>${money(second.price)} <small>/ box</small></strong></div></div><button class="add-button" data-view="${second.id}">Choose boxes</button></article>`);
  grid.querySelector("[data-home-prev]").onclick = event => { event.stopPropagation(); show(index - 1); restart(); }; grid.querySelector("[data-home-next]").onclick = event => { event.stopPropagation(); show(index + 1); restart(); }; dots.querySelectorAll("button").forEach((dot, i) => dot.onclick = event => { event.stopPropagation(); show(i); restart(); }); let startX = 0; image.ontouchstart = e => { e.stopPropagation(); startX = e.changedTouches[0].clientX; }; image.ontouchend = e => { e.stopPropagation(); const distance = e.changedTouches[0].clientX - startX; if (Math.abs(distance) > 40) { show(index + (distance < 0 ? 1 : -1)); restart(); } }; show(0); restart();
}
function renderCart() { const content = $("[data-cart-content]"); if (!content) return; $("[data-cart-count]").textContent = Cart.count(); const boxes = Cart.detailed(); content.innerHTML = boxes.length ? `<div class="cart-items">${boxes.map((box, index) => `<div class="cart-item" data-uid="${box.uid}"><img src="${box.image}" alt="Brownie Box"><div><h3>Box ${index + 1}</h3><p>9 brownies · ${money(box.price)}</p><label class="cart-customization">${box.sentence ? "Custom sentence" : "Add a custom sentence"}<input data-edit-sentence maxlength="60" value="${box.sentence.replaceAll('"', "&quot;")}" placeholder="Optional"></label><div class="qty"><button data-qty="-1" aria-label="Remove this box">−</button><span>1 box</span><button data-qty="1" aria-label="Duplicate this box">+</button><button class="remove" data-remove>Remove</button></div></div><strong>${money(box.price)}</strong></div>`).join("")}</div><div class="cart-total"><span>${boxes.length} ${boxes.length === 1 ? "box" : "boxes"} · ${Cart.pieces()} brownies</span><strong>${money(Cart.total())}</strong></div><p class="delivery-note">Delivery fees not included</p><button class="button button-dark full-button" data-checkout>Checkout / Order on WhatsApp</button>` : `<div class="empty-cart"><h3>Your cart is waiting.</h3><p>Add a box of brownies and make it yours.</p></div>`; bindCart(); }
function bindCart() { $$('[data-qty]').forEach(button => button.onclick = () => Cart.change(button.closest("[data-uid]").dataset.uid, Number(button.dataset.qty))); $$('[data-remove]').forEach(button => button.onclick = () => Cart.remove(button.closest("[data-uid]").dataset.uid)); $$('[data-edit-sentence]').forEach(input => input.oninput = () => { input.value = maxSentence(input.value); Cart.updateSilently(input.closest("[data-uid]").dataset.uid, input.value); }); $("[data-checkout]")?.addEventListener("click", () => { location.href = "checkout.html"; }); }
function showMobileCartPreview() { const preview = $(".mobile-cart-preview") || document.body.appendChild(Object.assign(document.createElement("div"), { className: "mobile-cart-preview" })); preview.innerHTML = `<div><strong>${Cart.count()} ${Cart.count() === 1 ? "box" : "boxes"}</strong><span>${money(Cart.total())}</span></div><button class="button preview-checkout">View cart</button>`; preview.classList.add("is-visible"); preview.querySelector(".preview-checkout").onclick = openCart; }
function openCart() { $(".cart-drawer")?.classList.add("is-open"); $(".drawer-backdrop")?.classList.add("is-open"); renderCart(); }
function closeCart() { $(".cart-drawer")?.classList.remove("is-open"); $(".drawer-backdrop")?.classList.remove("is-open"); }
function renderSummary() { const summary = $("[data-summary]"); if (!summary) return; const boxes = Cart.detailed(); summary.innerHTML = `<p class="form-label">Order summary</p>${boxes.map((box, i) => `<div class="summary-row"><span>Box ${i + 1}<br><small>9 brownies · ${box.sentence ? `“${box.sentence}”` : "No custom sentence"}</small></span><strong>${money(box.price)}</strong></div>`).join("")}<div class="summary-row total-row"><span>${boxes.length} ${boxes.length === 1 ? "box" : "boxes"} · ${Cart.pieces()} brownies<br>Subtotal<br><small>Delivery fees not included</small></span><strong>${money(Cart.total())}</strong></div>`; }
function setupCheckout() { const form = $("#checkout-form"); if (!form) return; renderSummary(); form.onsubmit = event => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const error = $("[data-form-error]"); if (!form.checkValidity()) { error.textContent = "Please complete all required fields."; form.querySelector(":invalid").focus(); return; } const phone = data.phone.replace(/[\s()-]/g, ""); if (!/^01[0125]\d{8}$/.test(phone)) { error.textContent = "Please enter a valid Egyptian mobile number."; form.phone.focus(); return; } if (!Cart.count()) { error.textContent = "Your cart is empty."; return; } const order = Cart.detailed().map((box, i) => `*Box ${i + 1}*\n9 brownies\n${box.sentence ? `Custom sentence: “${box.sentence}”` : "No custom sentence"}\nPrice: ${money(box.price)}`).join("\n\n"); const message = `Hello! I'd like to place an order 🍫\n\n*Customer Details*\nName: ${data.name}\nPhone: ${data.phone}\nEmail: ${data.email}\n\n*Delivery Address*\nGovernorate: ${data.governorate}\nArea: ${data.area}\nStreet: ${data.street}\nBuilding: ${data.building}\nFloor: ${data.floor}\nApartment: ${data.apartment}${data.notes ? `\nNotes: ${data.notes}` : ""}\n\n*Order*\n${order}\n\n*Total*\n${Cart.count()} ${Cart.count() === 1 ? "box" : "boxes"} · ${Cart.pieces()} brownies\nSubtotal: ${money(Cart.total())}\nDelivery: Not included\n\nThank you! 🤎`; window.open(`https://wa.me/${BUSINESS_CONFIG.whatsapp}?text=${encodeURIComponent(message)}`, "_blank"); } }
Cart.changed = () => { renderCart(); labelCartItems(); if ($(".checkout-page")) renderSummary(); };
productCard(); renderCart(); labelCartItems(); setupCheckout();
$("[data-open-cart]")?.addEventListener("click", openCart); $$('[data-close-cart]').forEach(button => button.onclick = closeCart); $("[data-products]")?.addEventListener("click", event => { const target = event.target.closest("[data-view]"); if (target) location.href = target.dataset.view === "yin-yang-box" ? "yin-yang.html" : "product.html"; });
