const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const labelCartItems = () => { const counts = {}; Cart.detailed().forEach((box, i) => { counts[box.name] = (counts[box.name] || 0) + 1; const title = document.querySelectorAll(".cart-item h3")[i]; if (title) title.textContent = box.name + " " + counts[box.name]; }); };
const productId = document.body.dataset.productId || new URLSearchParams(location.search).get("product") || PRODUCTS[0].id;
const product = PRODUCTS.find(item => item.id === productId) || PRODUCTS[0];
document.title = product.name + " | Zee Box";
let galleryIndex = 0;
const gallery = product.gallery || [product.image];
function showGalleryImage(index) { galleryIndex = (index + gallery.length) % gallery.length; $("[data-product-image]").src = gallery[galleryIndex]; $("[data-gallery-dots]").querySelectorAll("[data-gallery-dot]").forEach((dot, i) => dot.classList.toggle("is-active", i === galleryIndex)); }
let galleryTimer;
function restartGallery() { clearInterval(galleryTimer); galleryTimer = setInterval(() => { showGalleryImage(galleryIndex + 1); restartGallery(); }, galleryIndex === 0 ? 5500 : 4500); }
function setupGallery() { $("[data-gallery-dots]").innerHTML = gallery.map((_, i) => "<button type=\"button\" data-gallery-dot aria-label=\"Show image " + (i + 1) + "\"></button>").join(""); $("[data-gallery-dots]").querySelectorAll("[data-gallery-dot]").forEach((dot, i) => dot.onclick = event => { event.stopPropagation(); showGalleryImage(i); restartGallery(); }); $("[data-gallery-prev]").onclick = event => { event.stopPropagation(); showGalleryImage(galleryIndex - 1); restartGallery(); }; $("[data-gallery-next]").onclick = event => { event.stopPropagation(); showGalleryImage(galleryIndex + 1); restartGallery(); }; let startX = 0; const image = $("[data-product-image]"); image.addEventListener("touchstart", event => { startX = event.changedTouches[0].clientX; }, { passive: true }); image.addEventListener("touchend", event => { const distance = event.changedTouches[0].clientX - startX; if (Math.abs(distance) > 40) { showGalleryImage(galleryIndex + (distance < 0 ? 1 : -1)); restartGallery(); } }, { passive: true }); }
setupGallery(); showGalleryImage(0); restartGallery();
const maxSentence = value => { let count = 0; return [...value].filter(char => /\s/.test(char) || ++count <= 30).join(""); };
$("[data-product-image]").src = product.image;
$("[data-product-name]").textContent = product.name;
$("[data-product-description]").textContent = product.description;
$("[data-product-pieces]").textContent = `${product.pieces} brownies per box`;
$("[data-product-price]").innerHTML = `${product.price.toLocaleString()} EGP <small>/ box</small>`;
function fields() { const count = Number($("[data-box-qty-value]").textContent); const values = $$('[data-box-sentence]').map(input => input.value); $("[data-box-fields]").innerHTML = Array.from({ length: count }, (_, i) => `<label class="box-customization"><span>Box ${i + 1} <small>Optional · this sentence is written on this box</small></span><input data-box-sentence maxlength="60" value="${(values[i] || "").replaceAll('"', "&quot;")}" placeholder="e.g. Happy Birthday Sarah"></label>`).join(""); $("[data-box-total]").textContent = `${count} ${count === 1 ? "box" : "boxes"} · ${count * 9} brownies`; }
function renderCart() { const boxes = Cart.detailed(); $("[data-cart-count]").textContent = Cart.count(); $("[data-cart-content]").innerHTML = boxes.length ? `<div class="cart-items">${boxes.map((box, index) => `<div class="cart-item" data-uid="${box.uid}"><img src="${box.image}" alt="Brownie Box"><div><h3>Box ${index + 1}</h3><p>9 brownies · ${box.price.toLocaleString()} EGP</p><label class="cart-customization">${box.sentence ? "Custom sentence" : "Add a custom sentence"}<input data-edit-sentence maxlength="60" value="${box.sentence.replaceAll('"', "&quot;")}" placeholder="Optional"></label><div class="qty"><button data-qty="-1" aria-label="Remove this box">−</button><span>1 box</span><button data-qty="1" aria-label="Duplicate this box">+</button><button class="remove" data-remove>Remove</button></div></div><strong>${box.price.toLocaleString()} EGP</strong></div>`).join("")}</div><div class="cart-total"><span>${Cart.count()} ${Cart.count() === 1 ? "box" : "boxes"} · ${Cart.pieces()} brownies</span><strong>${Cart.total().toLocaleString()} EGP</strong></div><p class="delivery-note">Delivery fees not included</p><a class="button full-button" href="checkout.html">Checkout / Order on WhatsApp</a>` : `<div class="empty-cart"><h3>Your cart is waiting.</h3><p>Add a box of brownies and make it yours.</p></div>`; bindCart(); }
function bindCart() { $$('[data-qty]').forEach(button => button.onclick = () => Cart.change(button.closest("[data-uid]").dataset.uid, Number(button.dataset.qty))); $$('[data-remove]').forEach(button => button.onclick = () => Cart.remove(button.closest("[data-uid]").dataset.uid)); $$('[data-edit-sentence]').forEach(input => input.oninput = () => { input.value = maxSentence(input.value); Cart.updateSilently(input.closest("[data-uid]").dataset.uid, input.value); }); }
fields(); Cart.changed = () => { renderCart(); labelCartItems(); }; renderCart(); labelCartItems();
$("[data-box-qty]").parentElement.parentElement.addEventListener("click", event => { const button = event.target.closest("[data-box-qty]"); if (!button) return; $("[data-box-qty-value]").textContent = Math.max(1, Math.min(20, Number($("[data-box-qty-value]").textContent) + Number(button.dataset.boxQty))); fields(); });
$("[data-box-fields]").addEventListener("input", event => { if (event.target.matches("[data-box-sentence]")) event.target.value = maxSentence(event.target.value); });
$("[data-product-add]").onclick = () => { Cart.addBoxes(product.id, $$('[data-box-sentence]').map(input => maxSentence(input.value))); renderCart(); $(".cart-drawer").classList.add("is-open"); $(".drawer-backdrop").classList.add("is-open"); };
$("[data-open-cart]").onclick = () => { $(".cart-drawer").classList.add("is-open"); $(".drawer-backdrop").classList.add("is-open"); renderCart(); };
$$('[data-close-cart]').forEach(button => button.onclick = () => { $(".cart-drawer").classList.remove("is-open"); $(".drawer-backdrop").classList.remove("is-open"); });
if (new URLSearchParams(location.search).get("cart") === "open" && Cart.count()) { $(".cart-drawer").classList.add("is-open"); $(".drawer-backdrop").classList.add("is-open"); }
